### ISSUE TITLE
Feature: Include app name in title of page

### ISSUE THREAD

**Issue by jspears** [electrode-io/generator-electrode#28]
This gives a more customized experience and makes chasing down how all this works easier.

Right now its "Untitled Electrode Web Application" which is wrong because we gave it a name in the setup.

**Comment by kbariotis** [comment]
Hello, I would like to help on this. Should the generator render the app's name directly into https://github.com/electrode-io/generator-electrode/blob/master/generators/webapp/templates/server/plugins/webapp/index.js#L138 or into https://github.com/electrode-io/generator-electrode/blob/master/generators/app/templates/config/default.json so it overrides the default one?

Thanks

**Comment by jchip** [comment]
Thanks, that'd be great.  It should be the one in `config/default.json`.
