### ISSUE TITLE
packages missing

### ISSUE THREAD

**Issue by fokkerone** [electrode-io/generator-electrode#37]
on 'gulp dev' i get these two errors
Error: Cannot find module 'flagged-respawn'
Error: Cannot find module 'findup-sync'

**Comment by jchip** [comment]
Thanks for reporting this.

Can you please provide the version of `node` and `npm` you are using, the steps you followed, and the full output?

**Comment by ananavati** [comment]
@fokkerone 

are you still facing this issue? if not could be please close the issue.

also can you please make sure your `node` and `npm` versions match to that of the pre-req's mentioned in the docs. http://www.electrode.io/docs/requirements.html
