### ISSUE TITLE
[Question] Redux?

### ISSUE THREAD

**Issue by tatemz** [electrode-io/generator-electrode#40]
Redux is prolly best to be considered on a per-project basis, but it'd be nice if it was encouraged by the electrode team by integrating into their boilerplates.

https://github.com/reactjs/redux

**Comment by ananavati** [comment]
@tatemz 

redux is already built-in to electrode 

reference on our docs:
http://www.electrode.io/docs/what_is_electrode.html#features

electrode-boilerplate code including `redux`:
https://github.com/electrode-io/electrode-boilerplate-universal-react-node/blob/master/client/app.jsx#L4

`yo electrode` generate app also includes `redux`: 
https://github.com/electrode-io/generator-electrode/blob/master/generators/app/templates/client/app.jsx#L9

**Comment by tatemz** [comment]
Thanks! [see comment](https://github.com/electrode-io/electrode-archetype-react-app/issues/33#issuecomment-253623890)
