### ISSUE TITLE
IndexRedirect and SSR

### ISSUE THREAD

**Issue by mini-eggs** [electrode-io/generator-electrode#41]
Just wrestled with this for a bit. Not sure what the issue is. Using IndexRedirect in the way I was messed up SSR.

Here's my routes w/ IndexRedirect
```
import React from "react";
import {Route,IndexRoute,IndexRedirect} from "react-router";
import {App} from "./components/app";
import Content from './components/content_1';

export const routes = (
  <Route path="/" component={App}>
    <IndexRedirect to="/content/home"/>
    <Route path="/:page/:inner" component={Content}/>
  </Route>
);
```

Here's a photo of the source code: http://i.imgur.com/a3GS1jd.jpg

Here's the working ssr w/o IndexRedirect
```
import React from "react";
import {Route,IndexRoute} from "react-router";
import {App} from "./components/app";
import Content from './components/content_1';

export const routes = (
  <Route path="/" component={App}>
    <IndexRoute to="/content/home" component={Content}/>
  </Route>
);
```

Photo of source code: http://i.imgur.com/tnQuoDk.jpg

**Comment by jchip** [comment]
hmmm... yes, I think this use case would break SSR since the redirect match by react-router would generate a 302 to the browser first, but I have to look in more details to confirm.

**Comment by mini-eggs** [comment]
Ah, that makes a lot of sense. Thanks jchip! 

I'm not too familiar w/ the inner workings of react-router.
