### ISSUE TITLE
Redux DevTools don't work

### ISSUE THREAD

**Issue by osenvosem** [electrode-io/generator-electrode#44]
MacOS 10.12.1 node 7.0.0

The state after `npm start`:
![screen shot 2016-10-27 at 10 40 05](https://cloud.githubusercontent.com/assets/6762673/19758737/24e3db9c-9c32-11e6-950a-2cb307531aaf.png)

And there are warnings.
```
(node:10644) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
staticPaths Plugin: static files path prefix "dist"
```

UPD: Oh, you just do not use Redux DevTools.
Why you haven't added Redux DevTools?
Why the project organised by the type, while the best practice is organising it by feature?
I noticed that hot-reloading (`gulp hot`) also don't work, WDS just reload the page.
Why you use Gulp while the best practice is using npm scripts with webpack?

**Comment by caoyangs** [comment]
Running in development mode will enable Redux Devtools.
`gulp dev` or `gulp hot`
https://github.com/electrode-io/electrode-boilerplate-universal-react-node#run
