### ISSUE TITLE
hapi.js icon in the demo app

### ISSUE THREAD

**Issue by osenvosem** [electrode-io/generator-electrode#51]
Image from the documentation
![nwel64l](https://cloud.githubusercontent.com/assets/6762673/19981073/6d4f3798-a211-11e6-95f1-8ddcc49042cb.png)

There is no hapi icon in the demo app:
![screen shot 2016-11-03 at 22 04 30](https://cloud.githubusercontent.com/assets/6762673/19981105/8e7ef250-a211-11e6-8821-5faee4c05f77.png)

**Comment by donsalari** [comment]
https://github.com/electrode-io/electrode-io.github.io/pull/337
